# Generated by Django 4.1.7 on 2023-03-07 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=3000)),
                ('requisitos', models.CharField(max_length=3000)),
                ('beneficios', models.CharField(max_length=3000)),
                ('nivel', models.CharField(choices=[('ESTAGIO', 'Estagio'), ('TRAINEE', 'Trainee'), ('JUNIOR', 'Junior'), ('ANALISTA', 'Analista')], max_length=8)),
                ('contrato', models.CharField(choices=[('CLT', 'clt'), ('PJ', 'pj')], max_length=3)),
                ('duracao', models.CharField(choices=[('-6m', 'até 6 meses'), ('6m-1a', '6 meses - 1 ano'), ('1a-2a', '1 ano - 2 anos'), ('indeterm', 'indeterminado')], max_length=8)),
                ('salario', models.CharField(max_length=5)),
                ('modalidade', models.CharField(choices=[('REMOTO', 'remoto'), ('HIBRIDO', 'hibrido'), ('PRESENCIAL', 'presencial')], max_length=10)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('data_postagem', models.DateField(verbose_name='data de publicação')),
                ('link', models.CharField(max_length=3000)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
            ],
        ),
    ]
